#!/usr/bin/env python3
"""Generate the App Store rights-evidence document (HTML + PDF).

Reads scores-inventory.csv and emits appstore-evidence/rights-declaration.html
(+ .pdf when wkhtmltopdf is installed): a signed statement of rights plus a
piece-by-piece public-domain manifest of the complete catalog. Attach the PDF
in App Store Connect -> App Review Information when review asks for
documentary evidence of the right to use the sheet music.

  python3 scripts/build_evidence.py --name "Full Legal Name" --email you@example.com
"""
import argparse
import csv
import html
import os
import shutil
import subprocess
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INVENTORY = os.path.join(ROOT, "scores-inventory.csv")
OUT_DIR = os.path.join(ROOT, "appstore-evidence")

# Composer -> (full name, years, public-domain basis)
COMPOSERS = {
    "Traditional": ("Traditional", "—", "Traditional folk melody, no identifiable author, pre-20th century"),
    "H.E. Kayser": ("Heinrich Ernst Kayser", "1815–1888", "36 Elementary & Progressive Studies, Op. 20 (pub. c. 1848)"),
    "J.S. Bach": ("Johann Sebastian Bach", "1685–1750", "Composed by 1750"),
    "R. Kreutzer": ("Rodolphe Kreutzer", "1766–1831", "42 Études ou Caprices (pub. 1796)"),
    "Pierre Rode": ("Pierre Rode", "1774–1830", "24 Caprices, Op. 22 (pub. c. 1815)"),
    "L. van Beethoven": ("Ludwig van Beethoven", "1770–1827", "Symphony No. 9 (pub. 1824)"),
    "T.H. Bayly": ("Thomas Haynes Bayly", "1797–1839", "Long, Long Ago (pub. 1833)"),
    "J.A.P. Schulz": ("Johann Abraham Peter Schulz", "1747–1800", "Melody pub. 1794"),
    "R. Schumann": ("Robert Schumann", "1810–1856", "Album for the Young, Op. 68 (pub. 1848)"),
    "F.J. Gossec": ("François-Joseph Gossec", "1734–1829", "Gavotte (pub. c. 1786)"),
}

DECLARATION = """
<h2>1. What the app contains</h2>
<p>RosinTune is a violin practice tool: it listens through the microphone and
gives the player real-time pitch feedback against a target score. Its musical
content consists of <b>data files</b> (JSON) describing the notes of
public-domain musical works. The sheet music shown on screen is
<b>generated at runtime by the app's own music-engraving engine</b> from those
data files. The app contains <b>no scans, photographs, or reproductions of any
printed edition</b>, no lyrics, and no recordings of third-party
performances.</p>

<h2>2. Every musical work is in the public domain</h2>
<p>Every composition in the app and its content catalog is either a
traditional folk melody with no identifiable author or the work of a composer
who died in <b>1888 or earlier</b> (the most recent, Heinrich Ernst Kayser,
died over 135 years ago). Every work was first published before 1900. These
works are in the public domain in the United States (first published before
1930) and in all life-plus-70-years (and life-plus-100-years) jurisdictions.
A complete piece-by-piece manifest follows in the appendix.</p>

<h2>3. No third-party edition's content is reproduced</h2>
<p>Copyright in sheet music can subsist in a modern <i>edition</i> of a
public-domain work (its engraving/typesetting and an editor's added markings)
even when the composition itself is free. RosinTune reproduces neither:</p>
<ul>
<li><b>Engraving and layout</b> are produced entirely by the developer's own
software, at runtime, from the note data.</li>
<li><b>The note data</b> is that of the public-domain compositions
themselves, prepared with the developer's own conversion pipeline.</li>
<li><b>Editorial markings</b> displayed by the app (fingerings, string
numbers, bow-direction marks) are machine-generated by the developer's
conversion software — a standard first-position fingering table and
alternating bow-stroke assignment. In the étude collections, slurs and
articulations are the composers' own composition text (those studies were
written to teach exactly those bowing patterns); isolated remaining fingering
indications are standard, non-creative position assignments.</li>
</ul>

<h2>4. Titles and metadata</h2>
<p>The app and its App Store metadata identify works factually by composer and
work title (e.g. "Kayser — 36 Studies, Op. 20"). The app does not use the name
of any copyrighted method book, publisher, edition, or arranger, in the app or
in its metadata.</p>

<h2>5. Declaration</h2>
<p>I am the developer of RosinTune and the author of its score data files and
rendering software. To the best of my knowledge the app and its content
catalog contain no third-party copyrighted material, and I accept
responsibility for the content identified above. I am happy to provide any
further detail App Review may need.</p>
"""


def build_html(name, email):
    rows = list(csv.DictReader(open(INVENTORY, encoding="utf-8")))
    collections = {}
    for r in rows:
        collections.setdefault(r["Collection Title"], []).append(r)

    parts = []
    n = 0
    for coll_title in collections:
        parts.append(f'<h3>{html.escape(coll_title)}</h3>')
        parts.append("<table><tr><th>#</th><th>Title</th><th>Composer</th>"
                     "<th>Years</th><th>Public-domain basis</th>"
                     "<th>In app today</th></tr>")
        for r in collections[coll_title]:
            n += 1
            full, years, basis = COMPOSERS.get(
                r["Composer"], (r["Composer"], "?", "?"))
            live = "yes" if r["Stage"] == "published" else "catalog (not yet live)"
            parts.append(
                f"<tr><td>{n}</td><td>{html.escape(r['Title'])}</td>"
                f"<td>{html.escape(full)}</td><td>{years}</td>"
                f"<td>{html.escape(basis)}</td><td>{live}</td></tr>")
        parts.append("</table>")
    manifest = "\n".join(parts)

    today = date.today().strftime("%B %-d, %Y")
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; font-size: 11pt;
       margin: 36pt; color: #111; }}
h1 {{ font-size: 17pt; margin-bottom: 2pt; }}
h2 {{ font-size: 12.5pt; margin: 14pt 0 4pt; }}
h3 {{ font-size: 11.5pt; margin: 12pt 0 3pt; }}
.meta {{ color: #444; margin: 0 0 10pt; }}
table {{ border-collapse: collapse; width: 100%; font-size: 9pt; }}
th, td {{ border: 1px solid #bbb; padding: 2.5pt 5pt; text-align: left; }}
th {{ background: #f0f0f0; }}
.sig {{ margin-top: 18pt; }}
</style></head><body>
<h1>RosinTune — Statement of Rights for Musical Content</h1>
<p class="meta">Prepared by {html.escape(name)} ({html.escape(email)}) ·
{today} · App: RosinTune (iOS)</p>
{DECLARATION}
<p class="sig"><b>{html.escape(name)}</b><br>{html.escape(email)}<br>{today}</p>
<h2 style="page-break-before: always;">Appendix — complete piece manifest ({n} pieces)</h2>
<p>The manifest covers the developer's <i>entire</i> content catalog: pieces
marked "in app today" are currently visible in the app; the remainder are
prepared from the same public-domain works under the same policy and may be
published later.</p>
{manifest}
</body></html>"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--name", default="[Developer legal name]")
    ap.add_argument("--email", default="ypzhang@stoneridgetechnology.com")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    html_path = os.path.join(OUT_DIR, "rights-declaration.html")
    pdf_path = os.path.join(OUT_DIR, "rights-declaration.pdf")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(build_html(args.name, args.email))
    print(f"wrote {os.path.relpath(html_path, ROOT)}")

    if shutil.which("wkhtmltopdf"):
        r = subprocess.run(["wkhtmltopdf", "--quiet", "--enable-local-file-access",
                            html_path, pdf_path], capture_output=True, text=True)
        if r.returncode == 0:
            print(f"wrote {os.path.relpath(pdf_path, ROOT)}")
        else:
            print(f"wkhtmltopdf failed:\n{r.stderr}")
    else:
        print("wkhtmltopdf not found - open the HTML and print to PDF")


if __name__ == "__main__":
    main()
